import type { CaseRecord, EvidenceClaim, Localized, SourceRef } from "./schema";

const L = (en: string, ko: string): Localized => ({ en, ko });
const change = (note: Localized) => [{ date: "2026-09-13", note }];

const sources = {
  fbi2016: { title: "Update on Investigation of 1971 Hijacking by D.B. Cooper", publisher: "FBI Seattle", url: "https://www.fbi.gov/contact-us/field-offices/seattle/news/press-releases/update-on-investigation-of-1971-hijacking-by-d.b.-cooper" },
  fbiCase: { title: "D.B. Cooper Hijacking", publisher: "Federal Bureau of Investigation", url: "https://www.fbi.gov/history/cases-and-criminals/db-cooper-hijacking" },
  fbi2007: { title: "D.B. Cooper Redux", publisher: "Federal Bureau of Investigation", url: "https://archives.fbi.gov/archives/news/stories/2007/december/dbcooper_123107" },
  csd: { title: "FBI’s ‘One-In-A-Billion’ Parachute Returns And Revives D.B. Cooper Mystery", publisher: "Cowboy State Daily", url: "https://cowboystatedaily.com/2026/02/22/fbis-one-in-a-billion-parachute-returns-and-revives-d-b-cooper-mystery/" },
  vault: { title: "D.B. Cooper Part 51", publisher: "FBI Vault", url: "https://vault.fbi.gov/D-B-Cooper%20/d.b.-cooper-part-51/view" },
  cooperWiki: { title: "D. B. Cooper — FBI Evidence Review citation", publisher: "Wikipedia", url: "https://en.wikipedia.org/wiki/D._B._Cooper" },
  halt: { title: "Halt Memorandum — public copy and transcription", publisher: "Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/File:Halt_Memorandum.jpg" },
  rendleshamWiki: { title: "Rendlesham Forest incident — sceptical analysis", publisher: "Wikipedia", url: "https://en.wikipedia.org/wiki/Rendlesham_Forest_incident" },
  boone: { title: "Rendlesham Forest binary code analysis", publisher: "Kevin Boone", url: "https://kevinboone.me/rendelsham-binary.html" },
  ridpathLight: { title: "Rendlesham — flashing light analysis", publisher: "Ian Ridpath", url: "http://www.ianridpath.com/ufo/rendlesham2.html" },
  ridpathRadiation: { title: "Rendlesham — radiation analysis", publisher: "Ian Ridpath", url: "http://www.ianridpath.com/ufo/rendlesham4.html" },
  debate: { title: "Rendlesham Forest Incident 1980 – Radiation Readings", publisher: "The Debate", url: "https://thedebate.org/2019/09/03/rendlesham-forest-incident-1980-radiation-readings-important-new-information/" },
  otago: { title: "First eDNA study of Loch Ness points to something fishy", publisher: "University of Otago", url: "https://www.otago.ac.nz/news/newsroom/first-edna-study-of-loch-ness-points-to-something-fishy" },
  foxon: { title: "The Largest Eel? A Statistical Analysis", publisher: "JMIRx Bio", url: "https://xbio.jmir.org/2023/1/e49063" },
  illumina: { title: "Back to the drawing board: Loch Ness eDNA", publisher: "Illumina", url: "https://www.illumina.com/company/news-center/feature-articles/loch-ness-edna.html" },
  nova: { title: "Birth of a Legend 3", publisher: "PBS NOVA", url: "https://www.pbs.org/wgbh/nova/lochness/legend3.html" },
} satisfies Record<string, SourceRef>;

export const cooperClaims: EvidenceClaim[] = [
  {
    id: "C01", status: "CONFIRMED",
    claim: L("The FBI announced that it redirected active investigative resources while continuing to accept specific physical evidence.", "FBI가 적극 수사 자원을 전환하고 특정 물증은 계속 받겠다고 발표했다."),
    reason: L("The agency statement was checked directly; it is not presented as a complete view of all internal activity.", "직접 기관 원문으로 발표를 확인했다. 내부 업무의 실제 전체 진행까지 확인했다고 표현하지 않는다."),
    source: sources.fbi2016, sourceType: L("Primary — official agency statement", "1차 — 기관 공식 발표"), sourceDate: "2016-07-12",
    establishes: L("The policy the agency announced publicly.", "기관이 공개한 방침."),
    doesNotEstablish: L("An identification, Cooper’s death, or that no investigation occurred afterward.", "신원 확인, 범인의 사망, 이후 어떤 조사도 없었다는 사실."),
    counterEvidence: L("The FBI’s 2007 public request records an earlier period of active investigation; it is a different point in time, not contradictory new evidence.", "2007년 FBI 공개 협조 요청은 과거 적극 조사 상태다. 현재와 충돌하는 새 증거가 아니라 시점이 다른 기관 기록이다."),
    counterSource: sources.fbi2007, lastVerified: "2026-09-13",
    changeHistory: change(L("H-C1: policy change recorded; no identity status change.", "H-C1: 수사 방침 변화를 기록했으며 신원 상태 변경은 아니다.")),
  },
  {
    id: "C02", status: "UNVERIFIED",
    claim: L("Richard McCoy has been confirmed as D.B. Cooper.", "Richard McCoy가 Cooper로 확정됐다."),
    reason: L("The existence of a private claim and an official identification are kept separate; the two positions are not shown as equal evidence.", "주장의 존재와 확정 여부를 나눴다. 두 입장을 동등한 증거 강도로 표시하지 않는다."),
    source: sources.fbiCase, sourceType: L("Primary/closest — official case overview; publication date not stated", "1차/가장 가까운 자료 — 기관 사건 소개; 발행일 불명"), sourceDate: "NOT VERIFIED",
    establishes: L("The agency’s public account differs from the private identification claim.", "기관의 공개 설명과 사적 주장이 다르다."),
    doesNotEstablish: L("That the private claim became a new official identification.", "사적 주장이 새 공식 신원 결정으로 승격됐다는 사실."),
    counterEvidence: L("The FBI lists reasons for ruling McCoy out, including mismatches with two crew descriptions; the private claim cites similarities and interpretations of objects.", "FBI는 두 승무원의 묘사와 맞지 않았다는 등 배제 이유를 든다. 사적 주장 측에는 유사한 범행 방식과 물건 관련 해석이 있다."),
    counterSource: sources.csd, lastVerified: "2026-09-13",
    changeHistory: change(L("H-C2: new reporting was recorded, but identity status did not change.", "H-C2: 관련 새 보도이며 신원 상태 변경은 아님.")),
  },
  {
    id: "C03", status: "UNVERIFIED", statusQualifier: L("PRIMARY NOT FOUND · SECONDARY ONLY", "PRIMARY NOT FOUND · SECONDARY ONLY"),
    claim: L("The December 2025 return of a parachute authenticated it as Cooper’s parachute.", "2025년 12월 낙하산 반환이 Cooper의 낙하산이라는 인증이다."),
    reason: L("Returning or disposing of an object is separate from authenticating it; absence of authentication is not converted into a fake verdict.", "반환은 보관·처분 행위다. 진품 여부는 별도 검증 명제다. 인증 부재를 가짜 판정으로 바꾸지도 않는다."),
    source: sources.csd, sourceType: L("Secondary reporting; receipt, examination report and agency authentication not found", "2차 보도; 반환 영수증·감정 보고서·기관 인증문 미확보"), sourceDate: "2026-02-22",
    establishes: L("The owner described a return without a conclusion, and the report relays the FBI’s refusal to comment.", "소유자는 반환과 결론 미제시를 설명했고, 보도는 FBI의 논평 거절을 전한다."),
    doesNotEstablish: L("Authentication, official exclusion, or a direct agency statement that examination was inconclusive.", "인증, 공식 배제, 감정 결과가 무조건 불확정이었다는 기관 직접 발표."),
    counterEvidence: L("The report includes a contrary interpretation and a retired agent’s general view; the 2016 FBI policy also does not equate receipt with authentication.", "같은 기사에 반대 해석과 퇴직 요원의 일반론이 함께 있다. FBI의 2016년 방침도 접수만으로 인증하지 않는다."),
    counterSource: sources.fbi2016, lastVerified: "2026-09-13",
    changeHistory: change(L("H-C2: news item added; authentication remains unverified.", "H-C2: 새 소식 등록, 인증 상태 유지.")),
  },
  {
    id: "C04", status: "UNVERIFIED", statusQualifier: L("Strong counterevidence · PRIMARY IDENTIFIED, NOT RETRIEVED", "반대 자료 강함 · PRIMARY IDENTIFIED, NOT RETRIEVED"),
    claim: L("A usable Cooper DNA profile was obtained from the cigarette butts.", "담배꽁초에서 사용할 수 있는 Cooper DNA 프로필을 얻었다."),
    reason: L("Public counterevidence is strong, but the key internal record was not retrieved; neither CONFIRMED DNA nor a fully audited DEBUNKED status is used.", "공개 반대 자료는 강하지만 핵심 내부 원문을 직접 확보하지 못했다. CONFIRMED DNA도, 원문 완전 감사에 근거한 DEBUNKED도 쓰지 않는다."),
    source: sources.vault, sourceType: L("Primary identified, not retrieved; internal date not verified", "1차 자료 식별, 미열람; 내부 문서 날짜 미확인"), sourceDate: "NOT VERIFIED",
    establishes: L("There is strong counterevidence to the cigarette-butt DNA claim, while the checked FBI article identifies the tie as the DNA source.", "담배꽁초 DNA 보유 주장에 강한 반대 자료가 있고, 직접 확인한 기관 글의 DNA는 넥타이에서 나왔다."),
    doesNotEstablish: L("A review of every internal record, the exact disposal date or process, or the full current sample inventory.", "모든 내부 기록을 확인했다는 것, 폐기의 정확한 날짜·과정, 현재 보유 시료 전체."),
    counterEvidence: L("A cited FBI Evidence Review and a former case agent’s account indicate the butts were gone before DNA work; initial collection alone does not prove a successful profile.", "FBI Evidence Review 인용과 전 담당자 설명은 DNA 분석 추진 전에 물증이 폐기됐음을 가리킨다. 초기 수거 사실만으로 DNA 분석 성공을 주장할 수 없다."),
    counterSource: sources.cooperWiki, lastVerified: "2026-09-13",
    changeHistory: change(L("Corrected an AI cigarette-butt/tie mix-up; this is not a new forensic finding.", "AI의 담배꽁초/넥타이 혼동을 정정했으며 새 법과학 발견이 아니다.")),
  },
  {
    id: "C05", status: "UNVERIFIED",
    claim: L("DNA recovered from the tie must belong to Cooper.", "넥타이에서 얻은 DNA는 반드시 Cooper의 것이다."),
    reason: L("Evidence connecting the object to the person is required; ‘may not be his’ is not rewritten as ‘is not his.’", "물건과 사람을 연결하는 검증이 필요하다. ‘범인의 것이 아닐 수도 있음’을 ‘범인의 것이 아님’으로 바꾸지 않는다."),
    source: sources.fbi2007, sourceType: L("Primary — agency statement; raw analysis and complete custody history not obtained", "1차 — 기관 발표; 유전자 원표·완전한 취급 이력 미확보"), sourceDate: "2007-12-31",
    establishes: L("The agency described DNA derived from the tie.", "넥타이 유래 DNA라는 기관 설명."),
    doesNotEstablish: L("That the person who left the DNA was necessarily the hijacker.", "DNA를 남긴 사람이 범인이라는 필연성."),
    counterEvidence: L("A former agent discussed handling, contact routes and multiple contributors; that does not identify another donor either.", "취급·접촉 경로와 복수 기여 가능성에 관한 인터뷰 설명. 그것 역시 특정 다른 기증자의 신원 입증은 아니다."),
    counterSource: sources.csd, lastVerified: "2026-09-13",
    changeHistory: change(L("No new donor identification was verified in scope.", "이번 범위에서는 기증자 신원이 새로 확정된 변경을 확인하지 못했다.")),
  },
];

export const rendleshamClaims: EvidenceClaim[] = [
  {
    id: "R01", status: "CONFIRMED", statusQualifier: L("Limited to the content of the public document copy", "공개 문서 사본의 내용에 한정"),
    claim: L("A memo dated 13 January 1981 under Halt’s name records reports of unusual lights.", "1981-01-13자 Halt 명의 메모가 이상한 빛의 관측 보고를 기록한다."),
    reason: L("The observation recorded by the document is separated from an interpretation of the phenomenon; the copy’s full chain of custody remains unverified.", "문서 관찰과 현상 해석을 분리했다. 사본의 전체 보관 이력은 별도 미검증 속성이다."),
    source: sources.halt, sourceType: L("Contemporary agency document — third-party public copy", "당시 기관 문서 — 제3자 공개 사본"), sourceDate: "1981-01-13",
    establishes: L("The report appears in the document.", "문서에 해당 보고가 들어 있다."),
    doesNotEstablish: L("Independent verification of every sentence, an extraterrestrial origin, or that Halt directly witnessed the first-night events.", "모든 문장의 독립 검증, 물체의 외계 기원, 첫날 관측을 Halt가 직접 했다는 사실."),
    counterEvidence: L("Paragraph 1 summarizes other people’s reports; Halt’s participation and observation scope are described separately later.", "같은 문서 1항은 다른 사람들의 보고를 요약한다. 2·3항 참여·목격 범위는 말미에 따로 서술된다."),
    counterSource: sources.halt, lastVerified: "2026-09-13",
    changeHistory: change(L("Record created; not a new change to the document itself.", "이번 레코드 생성; 문서 자체의 새 상태 변경 아님.")),
  },
  {
    id: "R02", status: "UNVERIFIED",
    claim: L("The memo independently proves an extraterrestrial spacecraft landing.", "메모가 외계 우주선 착륙을 독립 입증한다."),
    reason: L("Witness seriousness or professional status cannot replace causal identification; unexplained details are not automatically evidence of an extraterrestrial cause.", "목격의 진지함이나 직업적 지위가 원인 규명의 대체물이 될 수 없다. 미해결 부분도 외계 해석의 증거로 자동 편입하지 않는다."),
    source: sources.halt, sourceType: L("Contemporary agency document — third-party public copy", "당시 기관 문서 — 제3자 공개 사본"), sourceDate: "1981-01-13",
    establishes: L("It records the observers’ reports.", "관측자들의 보고를 기록했다."),
    doesNotEstablish: L("Independent analysis of extraterrestrial material, machinery, or biology.", "외계 기원의 물질·장치·생물에 대한 독립 분석."),
    counterEvidence: L("Conventional explanations, including the lighthouse hypothesis, remain to be tested; they do not necessarily resolve every observation.", "등대 설명 등 통상적 설명은 검토 대상이며 모든 관측을 확정 해결한 증명은 아니다."),
    counterSource: sources.rendleshamWiki, lastVerified: "2026-09-13",
    changeHistory: change(L("No new verification of extraterrestrial origin was found within scope.", "새로운 외계 기원 검증은 이번 자료 범위에서 확인하지 못함.")),
  },
  {
    id: "R03", status: "DEBUNKED", statusQualifier: L("Only as a claim about this specific memo", "이 한 문서에 한정"),
    claim: L("Penniston’s binary code is written in the 1981 Halt memo.", "Penniston의 이진 코드가 1981년 Halt 메모에 적혀 있다."),
    reason: L("Whether the specified document contains the code can be checked directly; a later ASCII decoding does not authenticate transmission or date.", "한정된 문서 포함 여부는 직접 검사 가능하다. 후대 ASCII 해독의 성공만으로 전달 경로나 날짜가 인증되지는 않는다."),
    source: sources.halt, sourceType: L("Document inspection — full body of the public copy", "문서 직접 검사 — 공개 사본 본문 전체"), sourceDate: "1981-01-13",
    establishes: L("The specified memo does not contain a binary string or a report of receiving code.", "지정한 문서 안에는 이진 문자열·코드 수신 내용이 없다."),
    doesNotEstablish: L("That no 1980 personal notebook existed anywhere, deliberate fabrication, or that extraterrestrial communication is impossible.", "1980년 개인 노트가 어디에도 없었다는 사실, 고의 조작, 외계 통신의 불가능성."),
    counterEvidence: L("Later notebook and code claims exist; Boone did not compare his transcription bit-for-bit, and the original creation date is PRIMARY NOT FOUND.", "후대 노트·코드 주장은 존재한다. Boone도 전사를 모든 비트까지 대조하지 않았으며 원본 제작 시점은 PRIMARY NOT FOUND."),
    counterSource: sources.boone, lastVerified: "2026-09-13",
    changeHistory: change(L("The code-release chronology was reused; the original notebook date was not newly established.", "코드 공개 시점 설명을 재사용했으며 원 노트 제작 시점을 새로 확정하지 않았다.")),
  },
  {
    id: "R04", status: "SUPPORTED", statusQualifier: L("SECONDARY ONLY · PRIMARY IDENTIFIED, NOT RETRIEVED", "SECONDARY ONLY · PRIMARY IDENTIFIED, NOT RETRIEVED"),
    claim: L("Orford Ness lighthouse is a grounded explanation for some flashing-light observations.", "Orford Ness 등대는 일부 점멸광의 근거 있는 설명이다."),
    reason: L("The original analysis, full contemporary observations and geometry were not independently reproduced, so ‘the lighthouse solved the case’ is withheld.", "원 분석·당시 전체 관측·기하를 독립 재현하지 못했다. ‘등대였다, 사건 해결’이라는 강한 라벨은 보류."),
    source: sources.ridpathLight, sourceType: L("Primary analysis identified, not retrieved; secondary summary checked", "원 분석 식별, 미열람; 2차 요약 확인"), sourceDate: "NOT VERIFIED",
    establishes: L("A specific conventional hypothesis worth examining exists.", "검토할 만한 구체적 통상 가설이 있다."),
    doesNotEstablish: L("That every night, observation point and object had the same cause.", "모든 밤·모든 관측 지점·모든 물체가 동일한 원인이라는 사실."),
    counterEvidence: L("The memo reports multiple positions and movements that require further comparison; needing comparison is not itself a refutation.", "메모의 여러 위치·움직임 보고는 추가 대조를 요구한다. 다만 설명 요구가 곧 반증 성공은 아니다."),
    counterSource: sources.halt, lastVerified: "2026-09-13",
    changeHistory: change(L("Observation and later-analysis dates remain separate.", "관측 시기와 후대 분석 날짜를 합치지 않음.")),
  },
  {
    id: "R05", status: "UNVERIFIED",
    claim: L("The radiation values recorded in the memo alone prove an anomalous craft landed.", "메모에 기록한 방사선 값만으로 비정상 비행체 착륙이 입증된다."),
    reason: L("Neither a background-level explanation nor a later anomalous-value recollection resolves the other’s uncertainty; no health hazard or extraterrestrial origin is inferred.", "배경치라는 설명도, 비정상이라는 회고도 서로의 미검증을 해결해 주지 않는다. 이 자료로 건강 위해나 외계 기원을 판정하지 않는다."),
    source: sources.halt, sourceType: L("Contemporary document notation", "당시 문서의 수치 표기"), sourceDate: "1981-01-13",
    establishes: L("The memo’s reported numbers and notation: ‘0.1 milliroentgens’ and ‘.05-.07’; it does not include /hour.", "메모가 보고한 숫자와 표기: ‘0.1 milliroentgens’, ‘.05-.07’; 원문에는 /hour가 없다."),
    doesNotEstablish: L("Instrument model, calibration, adequate background control, isotope source, or the cause of a landing.", "기기 모델·교정 상태·적절한 배경 대조·동위원소 기원·착륙 원인."),
    counterEvidence: L("A later article reports different retrospective values and a correction hypothesis, but not contemporaneous independent calibration.", "후대 글은 다른 회고 수치와 보정 가설을 제시하지만 동시대 독립 교정 자료가 아니다."),
    counterSource: sources.debate, lastVerified: "2026-09-13",
    changeHistory: change(L("The 2019 recollection was added as material, not accepted as a confirmed change to the 1980 measurement.", "2019년 후대 진술은 자료 추가이며 1980년 측정값의 확정 변경으로 인정하지 않음.")),
  },
];

export const lochNessClaims: EvidenceClaim[] = [
  {
    id: "L01", status: "SUPPORTED",
    claim: L("The research team reported eel DNA but could not determine the animals’ size.", "연구팀은 장어 DNA를 보고했지만 크기를 결정하지 못했다."),
    reason: L("The institutional research announcement is distinguished from an independently reproduced experiment.", "연구 발표와 독립 실험 재현을 구분한다."),
    source: sources.otago, sourceType: L("Primary research-team announcement; raw data and full methods paper not obtained", "연구팀 1차 발표; 원 데이터·완전한 방법 논문 미확보"), sourceDate: "2019-09-05",
    establishes: L("The reported detection result and the researcher’s explicit limitation.", "발표된 검출 결과와 연구자의 명시적 제한."),
    doesNotEstablish: L("Individual size or the monster’s identity.", "개체 크기나 괴물의 정체."),
    counterEvidence: L("Size interpretation must be considered separately through the 2023 statistical paper.", "크기 해석은 2023년 별도 논문으로 검토해야 한다."),
    counterSource: sources.foxon, lastVerified: "2026-09-13",
    changeHistory: change(L("H-L1: later size analysis added; the eDNA observation was not withdrawn.", "H-L1: 후속 크기 분석 추가; eDNA 관측 철회가 아니다.")),
  },
  {
    id: "L02", status: "UNVERIFIED",
    claim: L("The 2019 results exclude every possible unidentified large animal.", "2019년 결과가 모든 가능성을 배제한다."),
    reason: L("The result is not extended beyond its observation scope; that limitation is also not positive evidence that an unidentified animal exists.", "관측 범위 밖으로 확대하지 않는다. 그렇다고 미확인 생물이 존재한다는 긍정 증거가 생기지는 않는다."),
    source: sources.otago, sourceType: L("Primary research-team announcement", "연구팀 1차 발표"), sourceDate: "2019-09-05",
    establishes: L("Non-detection within that sampling and analysis.", "해당 채집·분석에서의 비검출."),
    doesNotEstablish: L("Complete absence across all times, locations and organisms.", "전 시기·전 공간·모든 생물에 대한 완전한 부재."),
    counterEvidence: L("A 2025 interview discusses the single-time-point limitation and plans repeated collection.", "2025년 인터뷰는 단일 시점 조사 한계와 반복 수집 계획을 설명한다."),
    counterSource: sources.illumina, lastVerified: "2026-09-13",
    changeHistory: change(L("The follow-up plan does not withdraw the original result.", "후속 계획은 원 결과의 철회가 아님.")),
  },
  {
    id: "L03", status: "SUPPORTED",
    claim: L("Under the model, a giant eel is highly improbable, but biological impossibility was not proved.", "모델상 초대형 장어는 매우 개연성이 낮지만 생물학적 불가능성이 증명된 것은 아니다."),
    reason: L("The paper’s strong wording is not reused outside the model’s stated scope.", "저자의 강한 표현도 모델 범위를 벗겨서 재사용하지 않는다."),
    source: sources.foxon, sourceType: L("Primary — peer-reviewed statistical analysis; not a new sampling experiment", "1차 — 심사된 통계 분석; 새 채집 실험 아님"), sourceDate: "2023-07-21",
    establishes: L("Under the stated data and distribution assumptions, the very-large-eel explanation is weakened.", "명시한 자료·분포 가정하에서 매우 큰 장어 설명이 약해진다."),
    doesNotEstablish: L("The impossibility of every physiological growth path or every unidentified species.", "모든 생리적 성장 경로·모든 미확인 종의 불가능성."),
    counterEvidence: L("The paper’s limitations include 129 Loch Ness samples, distribution assumptions, exclusion of biological mechanisms and cross-environment comparison limits.", "논문 자체의 한계에는 Loch Ness 표본 129개, 분포 가정, 생물학적 기제 제외, 환경 간 비교 한계가 있다."),
    counterSource: sources.foxon, lastVerified: "2026-09-13",
    changeHistory: change(L("H-L1: added as separate evidence about size, not a retraction of eDNA findings.", "H-L1: eDNA 철회가 아닌 별도의 크기 근거로 추가.")),
  },
  {
    id: "L04", status: "SUPPORTED", statusQualifier: L("SECONDARY ONLY · primary recording and object NOT RETRIEVED", "SECONDARY ONLY · 원 녹음·현물 NOT RETRIEVED"),
    claim: L("The hoax account substantially weakens the surgeon’s photograph as evidence of a large unidentified animal.", "조작 설명은 이 사진을 대형 미확인 생물의 증거로 쓰는 것을 크게 약화한다."),
    reason: L("The account is strong, but the original confession recording and physical device were not verified here, so CONFIRMED is not used.", "조작 설명은 강하지만 원 고백·현물 검증을 완수한 것처럼 CONFIRMED를 쓰지 않는다."),
    source: sources.nova, sourceType: L("Secondary reconstruction with direct interview; primary recording and device not retrieved", "직접 인터뷰를 포함한 2차 재구성; 원 녹음·장치 미확보"), sourceDate: "2000-11",
    establishes: L("The basis and public history of the hoax explanation.", "조작 설명의 근거와 공개 경위."),
    doesNotEstablish: L("That every later sighting was a hoax.", "모든 후대 목격이 조작이라는 사실."),
    counterEvidence: L("The same page reports questions about the toy’s performance and timing of the confession; those questions do not restore the photo’s authenticity.", "같은 페이지는 장난감 성능·고백 공개 시점 문제도 전한다. 반대 의문만으로 사진의 진품성이 회복되지는 않는다."),
    counterSource: sources.nova, lastVerified: "2026-09-13",
    changeHistory: change(L("H-L2: evidence value narrowed without extending the conclusion to other sightings.", "H-L2: 증거 가치를 좁혔으며 다른 목격으로 결론을 확대하지 않음.")),
  },
  {
    id: "L05", status: "CONFIRMED", statusQualifier: L("Limited to what the interview announces", "인터뷰 내용에 한정"),
    claim: L("A 2025 interview introduces a new passive eDNA collection plan.", "2025년 인터뷰는 새로운 eDNA 수집 계획을 소개한다."),
    reason: L("The narrow proposition that a plan was announced can be checked directly.", "계획 발표라는 좁은 명제는 직접 확인 가능하다."),
    source: sources.illumina, sourceType: L("Direct interview published by a technology provider", "기술 제공 기업이 발행한 직접 인터뷰"), sourceDate: "2025-01-10",
    establishes: L("The proposed follow-up approach and plan.", "제시된 후속 접근과 계획."),
    doesNotEstablish: L("Completion, a new organism discovery, or the absence of every later result through 2026.", "계획 완료, 새 생물 발견, 2026년까지 모든 후속 결과의 부재."),
    counterEvidence: L("The earlier Otago result and later size analysis are separate; a plan article is not a research result.", "앞선 Otago 결과와 후속 크기 분석은 별개다. 계획 기사를 실제 연구 결과와 바꿔 끼우지 않는다."),
    counterSource: sources.otago, lastVerified: "2026-09-13",
    changeHistory: change(L("H-L3: plan announced; no discovery status change.", "H-L3: 계획 발표; 발견 상태 변경은 아님.")),
  },
];

const placeholder = (title: string): CaseRecord["images"] => [{
  role: "HERO", type: "PLACEHOLDER",
  alt: L(`${title}: no verified image available`, `${title}: 검증된 이미지 없음`),
  caption: L("No suitable verified image is included in this release candidate.", "이 출시 후보에는 적합성이 확인된 이미지가 포함되지 않았습니다."),
  provenance: L("Intentional placeholder; no generated, purchased, or unverified external image was substituted.", "의도적인 placeholder입니다. 생성·구매·미검증 외부 이미지를 대신 넣지 않았습니다."),
}];

export const researchedCases: CaseRecord[] = [
  {
    slug: "rendlesham", title: "Rendlesham Forest",
    subtitle: L("What does an official memo actually establish?", "공식 메모가 실제로 무엇을 입증하나?"),
    preview: L("A dated memo records unusual-light reports. It does not, by itself, identify an extraterrestrial cause.", "날짜가 적힌 메모는 이상한 빛의 보고를 기록한다. 그 문서만으로 외계 기원이 확인되는 것은 아니다."),
    status: L("Evidence disputed", "증거 해석 논쟁 중"), country: L("United Kingdom", "영국"), year: "1980–1981",
    categories: ["alone", "unexplained"], tags: ["UFO", "UAP", "memo", "radiation", "lighthouse", "미확인비행현상", "메모", "방사선", "등대"],
    aliases: ["Rendlesham Forest incident", "Britain's Roswell", "렌들셤 포리스트 사건"], people: ["Charles Halt", "Jim Penniston"], places: ["Rendlesham Forest", "Orford Ness"], dates: ["1980-12", "1981-01-13"], verifiedAt: "2026-09-13",
    images: placeholder("Rendlesham Forest"),
    narrative: [
      { id: "record", title: L("The record", "기록"), body: L("A public copy of the 13 January 1981 Halt memo was checked against its transcription. It records reports of unusual lights across three paragraphs. The first paragraph summarizes reports by other people; later paragraphs describe Halt’s own participation separately.", "1981년 1월 13일자 Halt 메모의 공개 사본을 전사와 대조했다. 문서는 세 항에 걸쳐 이상한 빛의 보고를 기록한다. 첫 항은 다른 사람들의 보고를 요약하고, 뒤 항은 Halt의 참여 범위를 따로 적는다."), sourceIds: ["halt"] },
      { id: "limits", title: L("Report is not cause", "보고는 원인 규명이 아니다"), body: L("An official document can establish that a report was recorded without independently proving what caused the observations. Conventional explanations, later binary-code claims and radiation interpretations therefore remain separate questions.", "공식 문서는 보고가 기록됐음을 보여줄 수 있지만 관측 원인을 독립적으로 입증하지는 않는다. 통상적 설명, 후대 이진 코드 주장, 방사선 해석은 각각 별도의 질문으로 다뤄야 한다."), sourceIds: ["halt", "rendlesham-wiki"] },
    ], claims: rendleshamClaims,
    sources: [
      { id: "halt", ...sources.halt, accessedAt: "2026-09-13" },
      { id: "rendlesham-wiki", ...sources.rendleshamWiki, accessedAt: "2026-09-13" },
      { id: "boone", ...sources.boone, accessedAt: "2026-09-13" },
      { id: "debate", ...sources.debate, accessedAt: "2026-09-13" },
    ],
    related: [
      { slug: "wow", relationType: "evidence_pattern", question: L("When does a recorded signal become evidence of a source?", "기록된 신호는 언제 원인의 증거가 되는가?") },
      { slug: "cooper", relationType: "evidence_pattern", question: L("What can an official file establish without solving identity?", "공식 기록은 신원을 풀지 못해도 무엇을 입증할 수 있는가?") },
    ],
  },
  {
    slug: "loch-ness", title: "Loch Ness Monster",
    subtitle: L("Did DNA research prove a monster—or a giant eel?", "DNA 연구가 괴물이나 거대 장어를 증명했나?"),
    preview: L("Eel DNA, statistical size analysis, a disputed photograph and a new collection plan answer different questions. None should be substituted for another.", "장어 DNA, 크기 통계 분석, 논쟁적인 사진, 새 수집 계획은 서로 다른 질문에 답한다. 하나를 다른 결과처럼 바꿔 읽어서는 안 된다."),
    status: L("Identity unverified", "정체 미확인"), country: L("Scotland, United Kingdom", "영국 스코틀랜드"), year: "1934–2025",
    categories: ["creatures", "unexplained"], tags: ["cryptid", "eDNA", "eel", "photograph", "크립티드", "환경DNA", "장어", "사진"],
    aliases: ["Nessie", "Loch Ness creature", "네시", "네스호 괴물"], people: ["Neil Gemmell", "Floe Foxon"], places: ["Loch Ness"], dates: ["1934", "2019-09-05", "2023-07-21", "2025-01-10"], verifiedAt: "2026-09-13",
    images: placeholder("Loch Ness Monster"),
    narrative: [
      { id: "questions", title: L("Four records, four questions", "네 기록, 네 질문"), body: L("The 2019 team announcement reports eel DNA but says the data do not reveal eel size. A 2023 paper models how improbable a very large eel would be under stated assumptions. A secondary reconstruction addresses the famous photograph. A 2025 interview introduces a passive eDNA collection plan.", "2019년 연구팀 발표는 장어 DNA를 보고하지만 크기는 알 수 없다고 명시한다. 2023년 논문은 명시된 가정 아래 매우 큰 장어의 개연성을 모델링한다. 2차 재구성은 유명 사진의 증거 가치를 다루고, 2025년 인터뷰는 수동 eDNA 수집 계획을 소개한다."), sourceIds: ["otago", "foxon", "nova", "illumina"] },
      { id: "boundaries", title: L("The boundaries matter", "경계가 중요하다"), body: L("A non-detection within sampling is not proof of absence everywhere. A statistical model is not a new field sample. A hoax account about one photograph does not decide every sighting. A research plan is not a discovery.", "표본에서의 비검출은 모든 시공간의 부재 증명이 아니다. 통계 모델은 새 현장 표본이 아니다. 사진 한 장의 조작 설명은 모든 목격을 결정하지 않는다. 연구 계획은 발견 결과가 아니다."), sourceIds: ["otago", "foxon", "nova", "illumina"] },
    ], claims: lochNessClaims,
    sources: [
      { id: "otago", ...sources.otago, accessedAt: "2026-09-13" },
      { id: "foxon", ...sources.foxon, accessedAt: "2026-09-13" },
      { id: "nova", ...sources.nova, accessedAt: "2026-09-13" },
      { id: "illumina", ...sources.illumina, accessedAt: "2026-09-13" },
    ],
    related: [
      { slug: "dyatlov", relationType: "evidence_pattern", question: L("How far can a supported model explain a whole incident?", "유력 모델은 사건 전체를 어디까지 설명할 수 있는가?") },
      { slug: "voynich", relationType: "evidence_pattern", question: L("What remains unknown after material evidence is established?", "물질적 증거를 확인한 뒤에도 무엇이 미확정으로 남는가?") },
    ],
  },
];
