import Image from 'next/image';
import Link from 'next/link';
import type {ReactNode} from 'react';
import type {Locale,CaseRecord} from '@/content/schema';
import type {ProductizedArticle,ProductizedBlock} from '@/content/productized';
import {cases} from '@/content';
import {editorialPhotoRecord} from '@/content/editorial-media';
import {assetUrl} from '@/lib/base-path';
import {isLaunchVisualExcluded} from '@/lib/launch-visual-exclusions';
import {genreLabel} from '@/content/taxonomy';
import draft from '../../../shared/editorial/romanov-reader.json';
import aliases from '../../../shared/editorial/romanov-anchors.json';
import originalsJson from '../../../shared/editorial/original-reader-copy.json';
import {ProductClaim} from './ProductizedArticleView';
import {EvidenceCard} from './EvidenceCard';
import {ReadingProgressTracker} from './ReadingProgressTracker';
import {ArticleToolbar,ArticleEnd} from './ArticleNavigation';
import {ArticlePanels} from './ArticlePanels';
import {panelForBlock,type ArticlePanelId} from '@/lib/article-panel-contract';
const paragraphs=(text:string)=>text.split(/\n\s*\n|\n/).filter(Boolean).map((s,i)=><p key={i}>{s.split(/\*\*(.*?)\*\*/g).map((part,j)=>j%2?<strong key={j}>{part}</strong>:part)}</p>);
export function CommonArticleView({article,record,locale}:{article?:ProductizedArticle;record:CaseRecord;locale:Locale}){
 const id=record.slug,copy=article?.localizedCopy[locale],romanov=id==='romanov-remains-dna',title=romanov&&locale==='ko'?draft.title:copy?.headline??record.displayTitle?.[locale]??record.title;
 const photo=editorialPhotoRecord(id,'THUMBNAIL'),photoPanel=id==='john-snow-broad-street'?'evidence':'story';
 const related=[...new Set([...(article?.metadata.relatedCases??[]),...record.related.map(r=>r.slug),...cases.filter(r=>r.slug!==id&&r.categories.some(c=>record.categories.includes(c))).map(r=>r.slug)])].filter(s=>s!==id&&cases.some(r=>r.slug===s)).slice(0,2);
 const blocks=(panel:ArticlePanelId)=>copy?.blocks.filter(b=>panelForBlock(b)===panel)??[];
 const chapters=(items:ProductizedBlock[])=>items.map(b=><section key={b.blockId} id={'block-'+b.blockId} className="narrative-chapter"><h2>{locale==='ko'?b.headingKo:b.headingEn}</h2>{paragraphs(locale==='ko'?b.textKo:b.textEn)}</section>);
 const empty=(ko:string,en:string)=><p className="panel-empty-note">{locale==='ko'?ko:en}</p>;
 const image=photo&&<figure className="abc-panel-photo"><a href={assetUrl('/editorial-media/'+photo.fileName)} target="_blank" rel="noreferrer" aria-label={locale==='ko'?'자료 원본 크게 보기':'Open original media'}><Image src={assetUrl('/editorial-media/'+photo.fileName)} alt={photo.alt[locale]} width={photo.width} height={photo.height} priority sizes="(max-width:780px) 100vw, 740px"/></a><figcaption>{photo.caption[locale]}<p className="photo-credit"><a href={photo.rights.sourcePage}>{(photo.rights.creditShort??photo.rights.author).split(/\s*[·/]\s*/)[0]}</a>{photo.rights.licenseUrl&&<> · <a href={photo.rights.licenseUrl}>{photo.rights.license}</a></>}</p><details><summary>{locale==='ko'?'자료 출처와 권리':'Media source and rights'}</summary><p>{photo.rights.credit}</p>{photo.notDepicted&&<p>{photo.notDepicted[locale]}</p>}<p>{photo.derivative?.modificationNotice[locale]}</p><a href={photo.rights.sourcePage}>{locale==='ko'?'원본 기록':'Source record'}</a>{photo.rights.licenseUrl&&<> · <a href={photo.rights.licenseUrl}>{photo.rights.license??'NASA media guidance'}</a></>}</details></figcaption></figure>;
 const diagrams=article?.visuals.filter(v=>!['HERO_CONTEXT','SOURCE_CONTEXT','SOURCE_MAP'].includes(v.role)&&!!(locale==='ko'?v.captionKo:v.captionEn)?.trim()&&!isLaunchVisualExcluded(v.localizedFiles[locale].fileName))??[];
 const originalCopy=(originalsJson as Record<string,Record<Locale,{blocks:ProductizedBlock[]}>>)[id]?.[locale]??(romanov?copy:undefined);
 const panels:Record<ArticlePanelId,ReactNode>={
 story:<section id="narrative" className="narrative">{photoPanel==='story'&&image}<div className="abc-panel-intro">{romanov&&<span id="block-scene-01" data-anchor-alias="intro" className="anchor-alias"/>}{paragraphs(romanov&&locale==='ko'?draft.intro:copy?.hook??record.subtitle[locale])}</div>{article?(romanov&&locale==='ko'?draft.sections.map(s=><section key={s.id} id={'block-'+s.id} className="narrative-chapter">{Object.entries(aliases.old_to_new_block_anchors).filter(([old,target])=>target===s.id && blocks('story').some(b=>b.blockId===old)).map(([old])=><span key={old} id={'block-'+old} data-anchor-alias={s.id} className="anchor-alias"/>)}<h2>{s.title}</h2>{paragraphs(s.text)}</section>):chapters(blocks('story'))):record.narrative.map(s=><section key={s.id} id={'block-'+s.id} className="narrative-chapter"><h2>{s.title[locale]}</h2>{paragraphs(s.body[locale])}</section>)}</section>,
 evidence:<section id="evidence" className="evidence-section">{photoPanel==='evidence'&&image}{chapters(blocks('evidence'))}{article?article.claims.map(c=><ProductClaim key={c.claimId} claim={c} article={article} locale={locale}/>):record.claims.map(c=><EvidenceCard key={c.id} claim={c} locale={locale} caseId={id}/>)}{diagrams.length>0&&<details className="abc-methods"><summary>{locale==='ko'?'보조 설명 도표 보기':'Supplementary diagrams'}</summary>{diagrams.map(v=><figure key={v.assetId}><Image src={assetUrl('/media/'+v.localizedFiles[locale].fileName)} alt={(locale==='ko'?v.altKo:v.altEn)??(locale==='ko'?v.captionKo:v.captionEn)} width={v.localizedFiles[locale].width} height={v.localizedFiles[locale].height}/><figcaption>{locale==='ko'?v.captionKo:v.captionEn}<p>{locale==='ko'?'자체 제작 설명 도표 · 증거 사진 아님':'Original explanatory graphic, not an evidence photograph'}</p>{v.sourceRefs.map(s=><a key={s} href={'#source-'+s}>{article!.sources.find(x=>x.sourceId===s)?.title??s} </a>)}</figcaption></figure>)}</details>}</section>,
 counterarguments:<section id="counterarguments" className="narrative">{article?(blocks('counterarguments').length?chapters(blocks('counterarguments')):empty('기존 원고에 별도로 분류된 반론 문단은 없습니다. 증거와 현재 확인된 범위에서 자료의 한계를 확인할 수 있습니다.','No separately classified counterargument is supplied. Read the evidence and current limitations.')):record.claims.filter(c=>c.counterEvidence[locale]?.trim()).map(c=><section key={c.id} className="narrative-chapter"><h2>{c.claim[locale]}</h2>{paragraphs(c.counterEvidence[locale])}{c.counterSource&&<a href={c.counterSource.url}>{c.counterSource.title}</a>}</section>)}</section>,
 current:<section id="fact-boundary" className="narrative">{chapters(blocks('current'))}{copy?.factBoundary&&<><h2>{locale==='ko'?'확인된 것':'Established'}</h2>{paragraphs(copy.factBoundary.established)}<h2>{locale==='ko'?'남은 의문':'Remaining questions'}</h2>{paragraphs(copy.factBoundary.notEstablished)}</>}{!article&&record.claims.map(c=><section key={c.id} className="narrative-chapter"><h2>{c.claim[locale]}</h2>{paragraphs(c.establishes[locale])}{paragraphs(c.doesNotEstablish[locale])}</section>)}{article&&!blocks('current').length&&!copy?.factBoundary&&empty('기존 원고에 현재 상태를 별도로 정리한 내용이 없습니다. 새 결론을 추가하지 않았습니다.','No separate current-status text is supplied; no new conclusion has been added.')}</section>,
 sources:<section id="sources" className="sources-section"><h2>{locale==='ko'?'자료와 출처':'Sources'}</h2><ol>{article?article.sources.map(s=><li key={s.sourceId} id={'source-'+s.sourceId}><a href={s.url} target="_blank" rel="noreferrer"><strong>{s.title}</strong><span>{s.publisher} ↗</span></a></li>):record.sources.map(s=><li key={s.id} id={'source-'+s.id}><a href={s.url} target="_blank" rel="noreferrer"><strong>{s.title}</strong><span>{s.publisher} · {s.accessedAt} ↗</span></a></li>)}</ol>{originalCopy&&<details className="abc-methods"><summary>{locale==='ko'?'편집 전 원문과 상세 설명':'Original wording and detailed explanations'}</summary>{originalCopy.blocks.map(b=><section key={b.blockId}><h3>{locale==='ko'?b.headingKo:b.headingEn}</h3>{paragraphs(locale==='ko'?b.textKo:b.textEn)}</section>)}</details>}<ArticleEnd locale={locale}>{related.map(slug=>{const r=cases.find(r=>r.slug===slug)!;return <p key={slug}><Link href={'/'+locale+'/cases/'+slug+'/'}>{r.displayTitle?.[locale]??r.title} →</Link></p>})}</ArticleEnd></section>};
 return <article className="case-page productized-page abc-reader" data-canonical-id={id}><ReadingProgressTracker canonicalId={id} locale={locale}/><ArticleToolbar id={id} title={title} locale={locale}/><header className="abc-article-header"><p className="kicker">{article?genreLabel(article.metadata.primaryGenre,locale):locale==='ko'?'사건 이야기':'Story'}</p><h1>{title}</h1></header><ArticlePanels locale={locale} caseId={id} panels={panels}/></article>;
}
